### ISSUE TITLE
boringssl aesni use

### ISSUE THREAD

**Issue by leonidgurevich** [google/shaka-packager#431] opened 2018-07-11 17:32 UTC
Hi,
Hope this is the place to ask:
I've found out that if aesni is available and in use for various set of ciphers, the ctr cipher still doesn't do it. 
Any particular reason, why? And are there any plans to add aesni support for ctr? 

Thanks!

**Comment by kqyang** [comment] 2018-07-11 19:20
This is a duplicate of #198. 

We do want to support aesni to take advantage of hardware accelerated instructions. Unfortunately we don't have any bandwidth to work on this right now.

We welcome and appreciate any contributions! If you'd like to help, let us know :)

**Closed by kqyang** 2018-07-11 19:20 UTC
Labels: needs triage
