### ISSUE TITLE
Unplayable packaged VOD with non-zero start-time

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#443] opened 2018-07-26 21:12 UTC
## System info
**Operating System**: latest debian
**Shaka Packager Version**: latest master

## Issue and steps to reproduce the problem
I am trying to package VOD which does not start at PTS 0, but rather `17038.456`. This time is also reflected in the subtitle vtt file so that the subtitle starts at `04:43:58.401`. But the packaged content is not playbale. Is this an issue with shaka packager, shaka player or the content?

**Packager Command**:
```
packager  'in=/data/assets/channels//tv-brasil-hd-1/recordings/2018/07/26/2018-07-26-17-15-3390234-misterios-de-entrever/output.mp4,stream=0,init_segment=2018-07-26-17-15-3390234-misterios-de-entrever_video_640_360.mp4,segment_template=video_640_360/video_640_360_2018-07-26-17-15-3390234-misterios-de-entrever-$Number$.mp4' 'in=/data/assets/channels//tv-brasil-hd-1/recordings/2018/07/26/2018-07-26-17-15-3390234-misterios-de-entrever/output.mp4,stream=1,init_segment=2018-07-26-17-15-3390234-misterios-de-entrever_video_720_410.mp4,segment_template=video_720_410/video_720_410_2018-07-26-17-15-3390234-misterios-de-entrever-$Number$.mp4' 'in=/data/assets/channels//tv-brasil-hd-1/recordings/2018/07/26/2018-07-26-17-15-3390234-misterios-de-entrever/output.mp4,stream=2,init_segment=2018-07-26-17-15-3390234-misterios-de-entrever_video_1920_1080.mp4,segment_template=video_1920_1080/video_1920_1080_2018-07-26-17-15-3390234-misterios-de-entrever-$Number$.mp4' 'in=/data/assets/channels//tv-brasil-hd-1/recordings/2018/07/26/2018-07-26-17-15-3390234-misterios-de-entrever/output.mp4,stream=3,language=por,init_segment=2018-07-26-17-15-3390234-misterios-de-entrever_audio_por.mp4,segment_template=audio/audio_por_2018-07-26-17-15-3390234-misterios-de-entrever-$Number$.mp4' 'in=/data/assets/channels//tv-brasil-hd-1/recordings/2018/07/26/2018-07-26-17-15-3390234-misterios-de-entrever/recording.vtt,stream=text,init_segment=2018-07-26-17-15-3390234-misterios-de-entrever_subtitle_init.mp4,segment_template=subtitle/ttv_$Number$.m4s,language=por' --mpd_output 2018-07-26-17-15-3390234-misterios-de-entrever.mpd  --hls_master_playlist_output 2018-07-26-17-15-3390234-misterios-de-entrever.m3u8 --generate_static_mpd --fragment_duration 3.2 --segment_duration 3.2  --suggested_presentation_delay 5 --min_buffer_time 3.2 --minimum_update_period 5 --default_language=por --allow_approximate_segment_timeline
```
**Extra steps to reproduce the problem?**
[recording.vtt.txt](https://github.com/google/shaka-packager/files/2233602/recording.vtt.txt) and mp4 file is https://goo.gl/fdyPk8

**What is the expected result?**
a packaged & playable content, instead it ends up stuck in shaka player right after load. 

Thank you

**Comment by kqyang** [comment] 2018-07-26 21:15
@jakubvojacek Do you have the packaged output available anywhere? It can save us some time running packaging :)

**Comment by kqyang** [comment] 2018-07-26 23:32
@jakubvojacek This is a problem in packager. There are empty edits in the inputs, which we were not handling previously. 

Coincidentally, we were working on EditList support last few weeks. I have just pushed the changes out. 

Let us know if you are still seeing problems with the latest change.

Closed as a duplicate of https://github.com/google/shaka-packager/issues/112.

**Closed by kqyang** 2018-07-26 23:32 UTC
Labels: duplicate

**Comment by jakubvojacek** [comment] 2018-07-27 12:43
@kqyang thank you, as always it works perfectly 👍
