### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by deeksha-shetty-24** [google/shaka-packager#623] opened 2019-07-18 11:14 UTC
I have hosted PlayReady in IIS and when i use packager in same machine with the below command it works.

`packager-win.exe input=h264_baseline_360p_600.mp4,stream=audio,output=audio.mp4 input=h264_baseline_360p_600.mp4,stream=video,output=h264_360p.mp4 --enable_playready_encryption --program_identifier "ae052c33-5ac4-4d84-96c7-ecdc322e3e72" --playready_server_url "https://localhost/PlayReadyNew/rightsmanager.asmx" --client_cert_file "ClientCertWithoutPrivKey.cer" --client_cert_private_key_file "ClientRootCA.pvk" --client_cert_private_key_password "yourPassword" --ca_file "ClientRootCA.cer" --mpd_output manifest.mpd`

But when packager is on different windows machine pointing to above server with same command getting below error.

```
ERROR:http_key_fetcher.cc(225)] curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
ERROR:packager_util.cc(156)] PlayReady encryption key source failed to fetch keys: 7 (HTTP_FAILURE): curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
ERROR:packager_main.cc(518)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Failed to create key source.
```

Could you please help on this?

**Comment by deeksha-shetty-24** [comment] 2019-07-19 12:17
Here is some details that may help to understand the situation better.

There are 2 machines involved here. One machine acts as a server (lets say Server-1) where play ready is hosted and there is one more machine lets say (Client-1) where we run the packager.

In Server-1 we did following - 

1. Created a self signed root CA certificate (lets say CA-1).
2. Add this to trusted store (via mmc as its a windows machine).
3. Generated a client certificate lets say C1.
4. Configured C1 in IIS as onToOneMappings.
5. Shared the C1 to Client-1.

(Referred - [this article](https://medium.com/@hafizmohammedg/configuring-client-certificates-on-iis-95aef4174ddb) for setting this up)

In Client-1 we did following - 

1. Ran packager with following command (parameters as per the example given) - 

packager-win.exe input=h264_baseline_360p_600.mp4,stream=audio,output=audio.mp4 input=h264_baseline_360p_600.mp4,stream=video,output=h264_360p.mp4 --enable_playready_encryption --program_identifier "ae052c33-5ac4-4d84-96c7-ecdc322e3e72" --playready_server_url "https://Server-1-IP/PlayReadyNew/rightsmanager.asmx" --client_cert_file "C1.cer" --client_cert_private_key_file "CA-1.pvk" --client_cert_private_key_password "CA-1 password" --ca_file "CA-1.cer" --mpd_output manifest.mpd

Note: Both server and client are in same private network.

With this we get `Peer certificate cannot be authenticated with given CA certificates.` error as mentioned in the OP.

We used both Windows & Linux machine as client to create the package and getting same error. 

As a diagnostic step, we tried following curl command in Client-1
`curl -v --cacert CA-1.cer https://Server-1-IP/PlayReadyNew/rightsmanager.asmx`
and we get following error for this
`*   Trying 192.168.1.12...
* TCP_NODELAY set
* Connected to 192.168.1.12 (192.168.1.12) port 443 (#0)
* schannel: SSL/TLS connection with 192.168.1.12 port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: using IP address, SNI is not supported by OS.
* schannel: sending initial handshake data: sending 156 bytes...
* schannel: sent initial handshake data: sent 156 bytes
* schannel: SSL/TLS connection with 192.168.1.12 port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with 192.168.1.12 port 443 (step 2/3)
* schannel: encrypted data got 1221
* schannel: encrypted data buffer: offset 1221 length 4096
* schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
* Closing connection 0
* schannel: shutting down SSL/TLS connection with 192.168.1.12 port 443
* schannel: clear security context handle
curl: (77) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.`
 
Let me know if you need any other information.

**Comment by kqyang** [comment] 2019-07-22 23:23
@deeksha-shetty-24 Based on this forum, you can declare your self-signed certificate trusted with standard WIndows means, see https://support.mobiletogether.com/default.aspx?g=posts&t=1100000154#post1100000461.

What happens if "--ca_file" is not specified? Does it fail on the same machine as well?

Btw, you can enable curl logging inside packager using "--v=2" option.

**Comment by deeksha-shetty-24** [comment] 2019-07-23 14:10
Thanks for your reply.

As suggested we tried on the same machine without  `--ca_file` and its still working. 

On the other machine we already added the certificate to trusted root by standard windows procedure and here with `--v=2` command this is what we get
```
[0723/193144:ERROR:http_key_fetcher.cc(225)] curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
[0723/193144:VERBOSE1:status.cc(74)] 7 (HTTP_FAILURE): curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
[0723/193144:VERBOSE1:playready_key_source.cc(184)] Server response:
[0723/193144:ERROR:packager_util.cc(156)] PlayReady encryption key source failed to fetch keys: 7 (HTTP_FAILURE): curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
[0723/193144:VERBOSE1:status.cc(74)] 3 (INVALID_ARGUMENT): Failed to create key source.
[0723/193144:ERROR:packager_main.cc(518)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Failed to create key source.
```

The curl request succeeds from other machine if we disable the certificate check with following command - 
`curl -k https://Server-1-IP/PlayReadyNew/rightsmanager.asmx`

Is there any way from packager to pass this parameter to curl? We don't want to disable the security though, it might help us temporarily.

**Comment by kqyang** [comment] 2019-07-23 18:35
@deeksha-shetty-24 I have added a flag to disable peer verification. Let us know if it works for you.

**Comment by deeksha-shetty-24** [comment] 2019-07-25 14:17
Thanks for the help. Though our issue haven't solved yet, we are able to diagnose it further with your changes.

**Comment by kqyang** [comment] 2019-07-25 17:29
Great to hear that it is helpful. I am closing this issue as the issue is related to the validity of the certificates. Feel free to reply if there is anything else we can help!

**Closed by kqyang** 2019-07-25 17:29 UTC
Labels: external
