### ISSUE TITLE
Shaka packager doesn't handle clear samples in encrypted track correctly

### ISSUE THREAD

**Issue by roticv** [google/shaka-packager#808] opened 2020-07-28 02:25 UTC
## System info
**Operating System**: centos 7
**Shaka Packager Version**: 1.6.0

## Issue and steps to reproduce the problem

I was reading ISO/IEC 23001-7:2016 and the source code of shaka packager and my conclusion is that shaka packager isn't implementing the logic of clear samples in encrypted track correctly.

Clause 6 from ISO/IEC 23001-7:2016 states

```
Each sample in a protected track SHALL be associated with an isProtected flag, Per_Sample_IV_Size, KID, optional Block pattern information, and an optional constant_IV. This can be accomplished by relying on the default values in the Track Encryption Box (‘tenc’) (see 8.2), and optionally specifying parameters by sample group. Encryption parameters specified in a sample group SHALL override the corresponding default parameter values for the samples in that group defined in the Track Encryption Box. Samples not mapped to any sample group SHALL use the defaults established in the Track Encryption Box.

When specifying the parameters by sample group, the Sample To Group Box (‘sbgp’) in the sample table or track fragment specifies which samples use which sample group description from the Sample Group Description Box (‘sgpd’). The format of the sample group description is uniform across all track types (as indicated by the handler type for the track). For fragmented files, it may be necessary to store both the Sample To Group Box and Sample Group Description Box in each track fragment to make them accessible for decryption of the samples they describe, e.g. when movie fragments are separately stored and delivered by streaming.
```

When reading through shaka packager's handling of clear samples, I don't see the logic to use seig information to override the default_isProtected value in tenc. This logic is handled correctly in chromium's source code (See TrackRunIterator::IsSampleEncrypted https://chromium.googlesource.com/chromium/src/media/+/master/formats/mp4/track_run_iterator.cc). 

Is it possible to port the logic from chromium to shaka-packager so it handles clear samples in encrypted track correctly

**Comment by kqyang** [comment] 2020-07-28 05:17
Thanks for bringing it up. We do support CENC sample groups, which is used for key rotation. 

We did not use CENC sample groups for clear lead intentionally as it was not supported on legacy devices, which we believe it is still the case. In practice, this gives the maximum support coverage across devices, across browsers.

I agree that it is not 100% compliant to the CENCv3 spec though we can argue that the clear lead is not part of the protected track. 

Is there another reason that you'd like us to switch to using CENC sample groups for the clear lead other than spec compliance?

**Comment by roticv** [comment] 2020-07-31 04:48
Yes, the main reason for bringing up this topic is because of spec compliance.

I came across this issue because I had some examples of accidental mixing of clear and drm content and shaka-packager wasn't coughing on the input. This led me to the specs to understand what's the correct mechanism for having a mix of clear and drm content and also the discovery that shaka-packager isn't spec compliant for handling clear samples in protected track.

**Comment by kqyang** [comment] 2020-07-31 05:07
Ok. Thanks for the info. I am closing this as working as intended as explained above.

**Closed by kqyang** 2020-07-31 05:07 UTC
Labels: working as intended

**Comment by roticv** [comment] 2020-07-31 17:11
Interesting: So the conclusion is that there is no intention for shaka-packager to adhere to specs? It seems easy to resolve (by backporting the fixes already in chromium). This is slightly disappointing to me

**Comment by kqyang** [comment] 2020-08-01 04:05
@roticv I may have misunderstood your request. 

Is your concern on Shaka Packager output with clear lead? Or is your concern on Shaka Packager's support on partially encrypted input?

For the former, as explained in https://github.com/google/shaka-packager/issues/808#issuecomment-664782348, it is a design choice to have the output with clear lead working on modern devices as well as legacy devices.

For the latter, what is the use case here?
