### ISSUE TITLE
Stand-alone pssh-box.py

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-packager#669] opened 2019-10-23 13:01 UTC
Would it be possible to create a stand-alone build of pssh-box.py?  I imagine that we could take the source version of pssh-box.py and bundle the protos into it somehow.  The result would be a single python script that we could publish next to the release binaries, so that it could be run without building Shaka Packager from source.

What do you think?  Would this be possible?  If it were possible, could we add this to future releases to simplify things for users of the binary releases?

**Comment by kqyang** [comment] 2019-10-23 15:51
There is already a feature request for something similar: https://github.com/google/shaka-packager/issues/550. It is mostly done, except the last step of including it in the build process and package it properly.

Btw, you can already build pssh-box.py alone without building the whole packager (https://github.com/google/shaka-packager/issues/538#issuecomment-459175358): 

```shell
ninja -C out/Release pssh_box_py
```

I'll close this issue as duplicate of https://github.com/google/shaka-packager/issues/550. Feel free to reopen if you want something different.

**Closed by kqyang** 2019-10-23 15:51 UTC
Labels: needs triage
