### ISSUE TITLE
Standalone/Static packager-linux

### ISSUE THREAD

**Issue by demetrius-tech** [google/shaka-packager#965] opened 2021-07-05 13:23 UTC
## System info
**Operating System**: Linux (RedHat, CentOS)
**Shaka Packager Version**: 2.5.0

## Issue and steps to reproduce the problem

Is it possible that you provide or building the standalone/static packager-linux with static libraries included without requiring external libraries for execution?

**Packager Command**:

Extra steps to reproduce the problem?
(1) Copy the packager-linux in a directory on RedHat
(2) Try to execute. 

What is the expected result?

Packager is executing.

What happens instead?

error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

**Comment by gregmsanderson** [comment] 2021-08-08 23:00
I'm finding the same problem.

I previously had 2.4.3 working fine on an EC2 with AWS's own Amazon Linux.

Seeing the recent updates you have released, I tried downloading the latest version to replace it with ...

wget https://github.com/google/shaka-packager/releases/download/v2.5.1/packager-linux

But when I run it now on the EC2, it complains:

`error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

So I tried installing that:

`sudo yum install libatomic`

And _that_ error went away, only to be replaced with a bunch of other ones:

```
packager: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by packager)
packager: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by packager)
packager: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by packager)
```

And indeed the AWS included glibc is an older version, from what I can see. Hmm. So it won't run.

Did 2.4.3 work because these libraries it needs _were_ included, and are no longer being?

I'm looking for the simplest upgrade option as simply swapping the binary does not work. Would it mean starting a new EC2 using e.g Ubuntu instead? Or compiling it myself (yikes)?

Thanks.

**Comment by joeyparrish** [comment] 2021-08-09 05:31
There must be a problem with the build infrastructure since moving it to GitHub Actions.  I'll take a look, and I'll replace the binaries on the releases page once I have figured out what went wrong.

Sorry for the trouble!

**Comment by joeyparrish** [comment] 2021-08-09 05:37
Confirmed on Linux:

```
$ wget https://github.com/google/shaka-packager/releases/download/v2.5.1/packager-linux
--2021-08-08 22:35:17--  https://github.com/google/shaka-packager/releases/download/v2.5.1/packager-linux
HTTP request sent, awaiting response... 200 OK
Length: 6336664 (6.0M) [application/octet-stream]
Saving to: ‘packager-linux’

$ file packager-linux 
packager-linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped

$ ldd packager-linux
        linux-vdso.so.1 (0x00007ffc431fd000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc3c6635000)
        libatomic.so.1 => /usr/lib/x86_64-linux-gnu/libatomic.so.1 (0x00007fc3c662b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc3c64dc000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc3c62fa000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc3c62df000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc3c60ed000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc3c6689000)
```

**Comment by joeyparrish** [comment] 2021-08-09 05:41
The Mac version seems okay.  Only standard, macOS libs/frameworks are linked in.  (I've recently learned from the docs that there is no such thing as a static executable from the Xcode toolchain, unless you're building the kernel.)

```
$ curl -LO https://github.com/google/shaka-packager/releases/download/v2.5.1/packager-osx

$ file packager-osx
packager-osx: Mach-O 64-bit executable x86_64

$ otool -L packager-osx
packager-osx:
        /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1671.60.107)
        /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.1.0)
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 158.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1575.17.0)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1575.17.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.255.3)
        /usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by joeyparrish** [comment] 2021-08-09 05:45
Just confirmed that the Mac build of v2.4.2 looked the same.

Windows looks okay, too.  No different from the v2.4.2 release.

```
$ wget https://github.com/google/shaka-packager/releases/download/v2.5.1/packager-win.exe
--2021-08-08 22:23:31--  https://github.com/google/shaka-packager/releases/download/v2.5.1/packager-win.exe
Resolving github.com (github.com)... 192.30.255.113
HTTP request sent, awaiting response... 200 OK
Length: 4456960 (4.2M) [application/octet-stream]
Saving to: ‘packager-win.exe’

$ file packager-win.exe 
packager-win.exe: PE32+ executable (console) x86-64, for MS Windows

$ chmod 755 packager-win.exe 

$ ldd packager-win.exe 
        ntdll.dll => /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff98bef0000)
        KERNEL32.DLL => /cygdrive/c/WINDOWS/System32/KERNEL32.DLL (0x7ff98b030000)
        KERNELBASE.dll => /cygdrive/c/WINDOWS/System32/KERNELBASE.dll (0x7ff989a10000)
        WS2_32.dll => /cygdrive/c/WINDOWS/System32/WS2_32.dll (0x7ff98aeb0000)
        RPCRT4.dll => /cygdrive/c/WINDOWS/System32/RPCRT4.dll (0x7ff98b480000)
        CRYPT32.dll => /cygdrive/c/WINDOWS/System32/CRYPT32.dll (0x7ff9897f0000)
        ucrtbase.dll => /cygdrive/c/WINDOWS/System32/ucrtbase.dll (0x7ff989e60000)
        SHLWAPI.dll => /cygdrive/c/WINDOWS/System32/SHLWAPI.dll (0x7ff98b390000)
        msvcrt.dll => /cygdrive/c/WINDOWS/System32/msvcrt.dll (0x7ff98a3e0000)
        WINMM.dll => /cygdrive/c/WINDOWS/SYSTEM32/WINMM.dll (0x7ff979dd0000)
        ADVAPI32.dll => /cygdrive/c/WINDOWS/System32/ADVAPI32.dll (0x7ff98ae00000)
        sechost.dll => /cygdrive/c/WINDOWS/System32/sechost.dll (0x7ff98a480000)
        ole32.dll => /cygdrive/c/WINDOWS/System32/ole32.dll (0x7ff98b680000)
        combase.dll => /cygdrive/c/WINDOWS/System32/combase.dll (0x7ff98bb50000)
        GDI32.dll => /cygdrive/c/WINDOWS/System32/GDI32.dll (0x7ff98b7b0000)
        win32u.dll => /cygdrive/c/WINDOWS/System32/win32u.dll (0x7ff989e30000)
        gdi32full.dll => /cygdrive/c/WINDOWS/System32/gdi32full.dll (0x7ff989630000)
        msvcp_win.dll => /cygdrive/c/WINDOWS/System32/msvcp_win.dll (0x7ff989ce0000)
        USER32.dll => /cygdrive/c/WINDOWS/System32/USER32.dll (0x7ff98b1e0000)
        CRYPTBASE.DLL => /cygdrive/c/WINDOWS/SYSTEM32/CRYPTBASE.DLL (0x7ff988fe0000)
```

**Comment by joeyparrish** [comment] 2021-08-09 05:48
I was making an assumption that the Linux builds had been truly static before I started making CI changes, but that's not the case.  libatomic was not in the dependency list before, but it wasn't fully static then, either.  Here's v2.4.2:

```
$ wget https://github.com/google/shaka-packager/releases/download/v2.4.2/packager-linux
--2021-08-08 22:46:10--  https://github.com/google/shaka-packager/releases/download/v2.4.2/packager-linux
Resolving github.com (github.com)... 192.30.255.113
HTTP request sent, awaiting response... 200 OK
Length: 6096968 (5.8M) [application/octet-stream]
Saving to: ‘packager-linux’

$ file packager-linux 
packager-linux: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, not stripped

$ ldd packager-linux 
        linux-vdso.so.1 (0x00007ffe8d4bc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f95617f9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f95617ee000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f95616aa000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f95614dd000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f95614c3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f95612fe000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f956183f000)
```

**Comment by gregmsanderson** [comment] 2021-08-09 13:50
Thanks @joeyparrish - yep, the Mac version works for me. It's the Linux one that's not happy.

**Closed** 2021-08-13 03:14 UTC
Labels: bug

**Comment by joeyparrish** [comment] 2021-08-13 03:56
Thanks for your patience.  We will push out a new release soon, which will have static binaries for linux.
