### ISSUE TITLE
Shaka Packager HLS iOS issue

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-packager#366] opened 2018-04-02 17:55 UTC
I am trying to use shaka packager streaming in iphone app.
I received the source code from CWIP support team also tested it with other sample mpd streams.
I made live stream .mpd file and m3u8 file from server and tried to use this on iOS app(CDM player).
When I made new .mpd file from mp4 file it plays well but live stream is not playing.
Here I made .mpd and .m3u8 file from udp://23.345.23.232:2333 stream.

But it doesn't play it.
Please resolve this problem.
Thanks.

**Comment by kqyang** [comment] 2018-04-02 18:18
Duplicate of #357. @WhiteDove101 Please don't create duplicated issues! Thanks.

**Closed by kqyang** 2018-04-02 18:18 UTC
