### ISSUE TITLE
[Question] Does FairPlay support multiple content keys?

### ISSUE THREAD

**Issue by weiyuefei** [google/shaka-packager#825] opened 2020-08-24 07:47 UTC
Hi, 

I'm trying to use a different content encryption key depending on whether the track is audio, standard def, or high def.  If I use a single key for all these tracks everything works fine.  But when different keys were used to encrypt the content, garbled video appeared in Safari as playback.   In the command below you will notice I'm actually using the same value for the key (only the key id is different) for all the tracks but even so it doesn't work. 

#!/bin/bash 
shopt -s expand_aliases

outputFileList=('A49546_E2_WS_XX_XX_480p_800kbps_en-US.mp4' 'A49546_E2_WS_XX_XX_480p_1500kbps_en-US.mp4' 'A49546_E2_WS_XX_XX_720p_1200kbps_en-US.mp4' 'A49546_E2_WS_XX_XX_720p_2000kbps_en-US.mp4' 'A49546_E2_WS_XX_XX_720p_3000kbps_en-US.mp4' )
audioOutput="A49546_E2_WS_XX_XX_en-US.mp4"

iv=00000000000000000000000000000001
au_key=0123456789abcdef0123456789abcde1
sd_key=0123456789abcdef0123456789abcde2
hd_key=0123456789abcdef0123456789abcde3
au_key_id=00000000000000000000000000000001
sd_key_id=00000000000000000000000000000002
hd_key_id=00000000000000000000000000000003

mkdir output6
cd output6

echo "now fairplay package the files"

packager input=../$audioOutput,stream=audio,drm_label=AUDIO,output=$audioOutput,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=English \
  input=../${outputFileList[0]},stream=video,drm_label=SD,output=${outputFileList[0]},playlist_name=vid1.m3u8 \
  input=../${outputFileList[1]},stream=video,drm_label=SD,output=${outputFileList[1]},playlist_name=vid2.m3u8 \
  input=../${outputFileList[2]},stream=video,drm_label=HD,output=${outputFileList[2]},playlist_name=vid3.m3u8 \
  input=../${outputFileList[3]},stream=video,drm_label=HD,output=${outputFileList[3]},playlist_name=vid4.m3u8 \
  input=../${outputFileList[4]},stream=video,drm_label=HD,output=${outputFileList[4]},playlist_name=vid5.m3u8 \
  --protection_scheme cbcs \
  --enable_raw_key_encryption \
  --keys label=AUDIO:key_id=$au_key_id:key=$au_key,label=SD:key_id=$sd_key_id:key=$sd_key,label=HD:key_id=$hd_key_id:key=$hd_key \
  --iv $iv \
  --hls_key_uri=skd://00000000000000000000000000000001 \
  --protection_systems FairPlay \
  --hls_master_playlist_output tears_master.m3u8

cd -

Can anyone provide some advice? Thanks

**Comment by kqyang** [comment] 2020-08-24 16:42
@weiyuefei What `hls_key_uri` are you using? What key is returned with that hls_key_uri?

This bug is related to #470.

**Comment by weiyuefei** [comment] 2020-08-25 01:36
> @weiyuefei What `hls_key_uri` are you using? What key is returned with that hls_key_uri?

In our use cases, it is the contentID right after `skd://`, that is, `hls_key_uri=skd://contentID` and currently we use the same key for all tracks of the content with `contentID` included in `hls_key_uri`.
  
> This bug is related to #470.

It is great that this feature is on roadmap, and looking forward to that.

**Comment by kqyang** [comment] 2020-08-25 04:46
@SeawardT Do you have any idea why it does not work even though they are actually using the same key, though with different key ids?

**Comment by kqyang** [comment] 2021-02-04 22:51
Mark it as a duplicate of #470.

**Closed by kqyang** 2021-02-04 22:51 UTC
Labels: needs triage
