### ISSUE TITLE
MPD compliance 

### ISSUE THREAD

**Issue by Tomtom777** [google/shaka-packager#105] opened 2016-05-19 13:30 UTC
Hello,

I had some troubles while trying to play a live 2 bitrates streams on GPAC's player then I ran a MPD validator on the manifest to see where the problem was (http://www-itec.uni-klu.ac.at/dash/?page_id=605). 

each time, it returned the following error, regardless of the number of streams I packaged:
```

<svrl:failed-assert test="if (@type=’dynamic’ and not(@id)) then false() else true()"
location="/*[local-name()='MPD' and namespace-uri()='urn:mpeg: dash:schema:mpd:2011']">
<svrl:text>If the MPD type is dynamic, the id shall be present </svrl:text>
</svrl:failed-assert>
Schematron validation not successful – DASH is not valid! Invalid
```

I past here the command I used to generate my MPD with one stream.

`./packager 'input=udp://127.0.0.1:1232,stream=video,init_segment=./stream/6/live-video-sd.mp4,segment_template=./6/live-video-sd-$Number$.mp4,bandwidth=2000000' --profile live --segment_duration=1 --single_segment=false --generate_dash_if_iop_compliant_mpd --mpd_output ./6/live.mpd 
`

To generate the udp stream, I used the medias given as example in edash-packager as ffmpeg inputs.

I noticed that the generated MPD is compatible with Bitmovin Bitdash player with 1-2 or 3 UDP live streams on packager's inputs

Thank you

**Comment by Tomtom777** [comment] 2016-05-19 13:34
I didn't past the error returned by GPAC
```
[DASH] No AdaptationSet could be selected in the MPD - Cannot play
 Cannot open live.mpd: BitStream Not Compliant

```
It happens only for several bitrates DASH streams
(Single-bitrate streams are readable)

**Comment by kqyang** [comment] 2016-05-19 17:15
This looks like a duplicate of #55, which has been fixed since version 1.3.0.

Can you try release v1.3.0 above? The latest release is [v1.4.0](https://github.com/google/shaka-packager/releases/tag/v1.4.0)

I am closing it for now. Feel free to re-open it if you are still seeing the problem.

**Comment by Tomtom777** [comment] 2016-05-20 08:17
I just tested with v1.3.0 and v1.3.1 but the MPD validator produces the same results as with the MPD generated yesterday with v1.4.0. 

Many thanks

**Comment by Tomtom777** [comment] 2016-05-20 10:51
It was you who closed the issue and I'm not sure to be able to reopen it 
thks

**Comment by kqyang** [comment] 2016-05-20 16:58
Em... Can you attach the generated manifest or email the generated manifest to me? You can find my email address in https://github.com/google/shaka-packager/blob/master/CONTRIBUTORS.

**Comment by kqyang** [comment] 2016-05-24 17:18
As discussed offline, there is a problem in http://www-itec.uni-klu.ac.at/dash/?page_id=605. MPD@id is optional but the validator is imposing unnecessary requirement on that. The owner of the validator has confirmed the problem and has fixed it. The mpd generated by edash-packager / shaka-packager should validate now.

Can you try again and see if it works now?

**Comment by Tomtom777** [comment] 2016-05-25 09:11
Thank you!

The MDP validation is now successful and the file is playable on GPAC's OSMO player

**Closed** 2016-05-25 09:11 UTC
