### ISSUE TITLE
Audio Decode errors on Fire TV with DRM packaging

### ISSUE THREAD

**Issue by simhavenkat** [google/shaka-packager#529] opened 2018-12-09 22:15 UTC
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
MacOS High Sierra for packaging, Amazon Fire TV for playback

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
master

## Issue and steps to reproduce the problem
The encrypted audio files generated by packager fail to play on Amazon Fire TV. They play fine in chrome, firefox etc. Adb logcat says

AAC decoder returned error 0x4007, substituting silence
AAC decoder returned error 0x4006, substituting silence

**Packager Command**:
packager \
    in=video1.mp4,stream=video,output=video1-enc.mp4,drm_label=DEF \
    in=video2.mp4,stream=video,output=video2-enc.mp4,drm_label=DEF \
    in=video3.mp4,stream=video,output=video3-enc.mp4,drm_label=DEF \
    in=video4.mp4,stream=video,output=video4-enc.mp4,drm_label=DEF \
    in=audio.mp4,stream=audio,output=audio-enc.mp4,drm_label=DEF \
    --enable_raw_key_encryption --keys DEF:key_id=<Removed>:key=<removed> \
    --pssh=<removed> \
    --mpd_output enc-manifest.xml

Extra steps to reproduce the problem?
(1) There are 2 manifests in the attached files. The clear-manifest plays fine. Running the packager on the clear media - generates the encrypted versions which throw the above error on audio
i have a sample app thats loading this manifest in Exo Player 2. I can share it if it helps. 

What is the expected result?
Playback succeeds.

What happens instead?
Playback fails once the silence substitution goes too far.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>
All the media files are at: https://drive.google.com/open?id=1ZzEUOXeTlZ6aiwZxCfom3L_eTdag2zUL

**Comment by kqyang** [comment] 2018-12-11 00:01
@simhavenkat It looks like a decryption problem. I have a few questions:

(1) Does the video play?

(2) 
> Playback fails once the silence substitution goes too far.

So does the audio play for a while then stops? How long does it play?

One thing you can try is to disable clear_lead, i.e. by setting it to 0 (--clear_lead=0). Some "old" devices / players have problem supporting contents with clear lead.

(3) Which Amazon Fire TV are you using? What is the Android version on the device?

(4) Have you tried it on other Android devices?

**Comment by simhavenkat** [comment] 2018-12-11 19:12
(1) Video plays for about 14 seconds and stops. If we scrub it plays for another 14 seconds and stops. 
(2) Audio does not play at all. The logcat spew points to the AAC error.
(2a) Yes i tried clear_lead = 0 already - that did not help.
(3) I am using the fire tv stick..
  (3a) Android 7.1
(4) Yes tried on Nvdia shield - same result. Video plays for 14s and stops until we scrub again.

**Comment by simhavenkat** [comment] 2018-12-11 19:14
Couple of other things i tried.
I tried the shaka packager to decrypt - the decrypted file and the original are different in file size. When i try to play the decrypted file - it says corrupt stream in ExoPlayer.

**Comment by astinus-1** [comment] 2018-12-11 22:51
Looking into the repro.

**Comment by kqyang** [comment] 2018-12-13 01:44
@simhavenkat Can you check if you have problem playing our public demo content available at https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;lang=en-US;build=uncompiled? For example, https://github.com/google/shaka-player/blob/master/demo/common/assets.js#L447:

Manifest: https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd
License Server: https://cwip-shaka-proxy.appspot.com/no_auth

**Comment by astinus-1** [comment] 2018-12-14 19:45
Repro notes so far:
Packager is giving EditList warnings:

packager \
> in=clear/video1.mp4,stream=video,output=encrypted/video1-enc.mp4,drm_label=DEF \
> in=clear/video2.mp4,stream=video,output=encrypted/video2-enc.mp4,drm_label=DEF \
> in=clear/video3.mp4,stream=video,output=encrypted/video3-enc.mp4,drm_label=DEF \
> in=clear/video4.mp4,stream=video,output=encrypted/video4-enc.mp4,drm_label=DEF \
> in=clear/audio.mp4,stream=audio,output=encrypted/audio-enc.mp4,drm_label=DEF \
> --enable_raw_key_encryption --keys DEF:key_id=30303030303030303030303030303031:key=78a1dc0646119707e903514d8a00735f \
> --pssh= \
> --mpd_output encrypted/enc-manifest.xml
[1212/182025:INFO:demuxer.cc(88)] Demuxer::Run() on file 'clear/audio.mp4'.
[1212/182025:INFO:demuxer.cc(88)] Demuxer::Run() on file 'clear/video1.mp4'.
[1212/182025:INFO:demuxer.cc(160)] Initialize Demuxer for file 'clear/audio.mp4'.
[1212/182025:INFO:demuxer.cc(160)] Initialize Demuxer for file 'clear/video1.mp4'.
[1212/182025:INFO:demuxer.cc(88)] Demuxer::Run() on file 'clear/video2.mp4'.
[1212/182025:INFO:demuxer.cc(160)] Initialize Demuxer for file 'clear/video2.mp4'.
[1212/182025:INFO:demuxer.cc(88)] Demuxer::Run() on file 'clear/video3.mp4'.
[1212/182025:INFO:demuxer.cc(160)] Initialize Demuxer for file 'clear/video3.mp4'.
[1212/182025:INFO:demuxer.cc(88)] Demuxer::Run() on file 'clear/video4.mp4'.
[1212/182025:INFO:demuxer.cc(160)] Initialize Demuxer for file 'clear/video4.mp4'.
[1212/182025:WARNING:track_run_iterator.cc(699)] Seeing non-zero composition offset 1024. An EditList is probably missing.
[1212/182025:WARNING:track_run_iterator.cc(703)] Adjusting timestamps by -1024. Please file a bug to https://github.com/google/shaka-packager/issues if you do not think it is right or if you are seeing any problems.
[1212/182025:WARNING:track_run_iterator.cc(699)] Seeing non-zero composition offset 1024. An EditList is probably missing.
[1212/182025:WARNING:track_run_iterator.cc(703)] Adjusting timestamps by -1024. Please file a bug to https://github.com/google/shaka-packager/issues if you do not think it is right or if you are seeing any problems.
[1212/182025:WARNING:track_run_iterator.cc(699)] Seeing non-zero composition offset 1024. An EditList is probably missing.
[1212/182025:WARNING:track_run_iterator.cc(703)] Adjusting timestamps by -1024. Please file a bug to https://github.com/google/shaka-packager/issues if you do not think it is right or if you are seeing any problems.
[1212/182025:WARNING:track_run_iterator.cc(699)] Seeing non-zero composition offset 1024. An EditList is probably missing.
[1212/182025:WARNING:track_run_iterator.cc(703)] Adjusting timestamps by -1024. Please file a bug to https://github.com/google/shaka-packager/issues if you do not think it is right or if you are seeing any problems.

Playback URL: https://integration.uat.widevine.com/player?autoPlay=true&contentUrl=https://storage.googleapis.com/wvtemp/kylealexander/packager_test/github_529/encrypted-me/enc-manifest.mpd&proxyServerUrl=https://proxy.uat.widevine.com/proxy%3Fck1=eKHcBkYRlwfpA1FNigBzXw

Link plays back successfully on Chrome. Updating an ExoPlayer app to try to play back on AndroidTV and FireTV.

**Comment by astinus-1** [comment] 2018-12-20 21:35
Confirmed that using ExoPlayer to play back the Playback URL is failing on Fire TV, but worked on Chrome.

**Comment by simhavenkat** [comment] 2018-12-21 04:21
Great - that looks like a repro of the proble. The demo content plays fine on fire tv in the webview.

**Comment by kqyang** [comment] 2018-12-21 21:19
@simhavenkat The repro uses clear key, for which the failure is expected as Android does not support clear key. Were you using a Widevine server or were you using clear key? 

> The demo content plays fine on fire tv in the webview.

Does it work in Exoplayer on fire tv?

**Comment by astinus-1** [comment] 2018-12-21 21:22
I retried, setting the clearly drm system in exoplayer, and confirmed my
content link plays.

**Comment by astinus-1** [comment] 2018-12-21 21:23
Clearly=clearkey

**Comment by astinus-1** [comment] 2018-12-21 23:01
I've confirmed that I can also create widevine raw key content, and play it back on FireTV:

Content Name: llama.mpd (24fps, 30fps)
Packager Version: packager version 3f7ecd4e29-release
Packager key: 3f7ecd4
Content ID (hex):    48656c6c6f4b6974747933663765636434
Content ID (ascii):  HelloKitty3f7ecd4
Protection Scheme:  cenc

PSSH Command: 
python pssh-box.py --widevine-system-id --content-id 48656c6c6f4b6974747933663765636434 --protection-scheme cenc --hex

Packager Command: 
packager input=./unencrypted/h264/llama_aac_audio.mp4,stream=audio,output=./encrypted/llama_aac_audio.mp4,drm_label=AUDIO input=./unencrypted/h264/llama_h264_baseline_240p_800.mp4,stream=video,output=./encrypted/llama_240p_24fps.mp4,drm_label=SD input=./unencrypted/h264/llama_h264_main_480p_2000.mp4,stream=video,output=./encrypted/llama_480p_24fps.mp4,drm_label=SD input=./unencrypted/h264/llama_h264_main_720p_8000.mp4,stream=video,output=./encrypted/llama_720p_24fps.mp4,drm_label=SD input=./unencrypted/h264/llama_h264_high_1080p_20000.mp4,stream=video,output=./encrypted/llama_1080p_24fps.mp4,drm_label=HD input=./unencrypted/h264/llama_h264_high_1080p_30fps_20000.mp4,stream=video,output=./encrypted/llama_1080p_30fps.mp4,drm_label=HD input=./unencrypted/h264/llama_h264_high_uhd_30000.mp4,stream=video,output=./encrypted/llama_2160p_24fps.mp4,drm_label=HD input=./unencrypted/h264/llama_h264_high_uhd_30fps_30000.mp4,stream=video,output=./encrypted/llama_2160p_30fps.mp4,drm_label=HD --enable_raw_key_encryption --protection_scheme cenc --keys label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead --pssh 000000337073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED00000013221148656C6C6F4B6974747933663765636434 --mpd_output ./encrypted/llama.mpd

Playback URL:
https://storage.googleapis.com/wvtest/shaka-packager/release-testing/v2.3/uat/3f7ecd4/raw_key/h264_cenc/llama.mpd

License URL:
https://proxy.staging.widevine.com/proxy?video_id=WVLS_RAWKEY_CAN_PLAY&provider=widevine_test

**Comment by simhavenkat** [comment] 2018-12-22 03:30
My failure was with widevine  - not clearkey - the content i uploaded has the manifest.

**Comment by simhavenkat** [comment] 2018-12-22 03:35
Ah - i see the diff - i called the widevine content encryption api to get the pssh and passed it to the packager as raw key. I played demo content using web view.

**Comment by kqyang** [comment] 2020-06-02 00:09
This issue is very old. I am closing the issue. @simhavenkat Please re-open if it is still a problem for you.

**Closed by kqyang** 2020-06-02 00:09 UTC
Labels: needs triage
