### ISSUE TITLE
[DASH] Support TrickPlay using separate trick play specific streams

### ISSUE THREAD

**Issue by ngbrown** [google/shaka-packager#732] opened 2020-03-16 16:45 UTC
## System info
**Operating System**: Windows 10 10.0.18362.657
**Shaka Packager Version**: v2.4.1-c731217607-release

## Issue and steps to reproduce the problem

**Packager Command**:

```cmd
packager-win.exe ^
in=audio_48k.m4a,stream=audio,output=output/audio_48k.m4a,playlist_name=output/audio_48k.m3u8,hls_group_id=audio,hls_name=ENGLISH ^
in=audio_128k.m4a,stream=audio,output=output/audio_128k.m4a,playlist_name=output/audio_128k.m3u8,hls_group_id=audio,hls_name=ENGLISH ^
in=360p.m4v,stream=video,output=output/360p.m4v,playlist_name=output/360p.m3u8,iframe_playlist_name=output/360p_iframe.m3u8 ^
in=480p.m4v,stream=video,output=output/480p.m4v,playlist_name=output/480p.m3u8,iframe_playlist_name=output/480p_iframe.m3u8 ^
in=720p.m4v,stream=video,output=output/720p.m4v,playlist_name=output/720p.m3u8,iframe_playlist_name=output/720p_iframe.m3u8 ^
in=1080p.m4v,stream=video,output=output/1080p.m4v,playlist_name=output/1080p.m3u8,iframe_playlist_name=output/1080p_iframe.m3u8 ^
in=trick_480p.m4v,stream=video,output=output/trick_480p.m4v,trick_play_factor=1,playlist_name=output/trick_480p.m3u8 ^
in=trick_1080p.m4v,stream=video,output=output/trick_1080p.m4v,trick_play_factor=1,playlist_name=output/trick_1080p.m3u8 ^
--hls_master_playlist_output output/master.m3u8 ^
--mpd_output output/master.mpd --generate_static_live_mpd
```

Extra steps to reproduce the problem?
1. Generate a separate trick play track instead of sharing with main video.  The main video has I-frames every 6 seconds, while the trick play track should be 1 fps with 1 I-Frame per second.
2. Run repeatedly

What is the expected result?

Sometimes it succeeds:

```
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file '1080p.m4v'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file '480p.m4v'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file '720p.m4v'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file 'audio_128k.m4a'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file '720p.m4v'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file 'audio_48k.m4a'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file '1080p.m4v'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file '480p.m4v'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file 'trick_1080p.m4v'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file '360p.m4v'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file 'audio_128k.m4a'.
[0316/093610:INFO:demuxer.cc(88)] Demuxer::Run() on file 'trick_480p.m4v'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file 'audio_48k.m4a'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file 'trick_1080p.m4v'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file '360p.m4v'.
[0316/093610:INFO:demuxer.cc(160)] Initialize Demuxer for file 'trick_480p.m4v'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/360p.m4v'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/audio_128k.m4a'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/audio_48k.m4a'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/trick_1080p.m4v'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/480p.m4v'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/trick_480p.m4v'.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/720p.m4v'.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/360p.m4v' finalized.
[0316/093611:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/1080p.m4v'.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/audio_128k.m4a' finalized.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/audio_48k.m4a' finalized.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/trick_1080p.m4v' finalized.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/1080p.m4v' finalized.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/trick_480p.m4v' finalized.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/480p.m4v' finalized.
[0316/093611:INFO:mp4_muxer.cc(177)] MP4 file 'output/720p.m4v' finalized.
Packaging completed successfully.
```

What happens instead?

Other times it fails:

```
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file '720p.m4v'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file 'audio_48k.m4a'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file 'audio_48k.m4a'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file '360p.m4v'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file '1080p.m4v'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file '480p.m4v'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file '480p.m4v'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file 'trick_480p.m4v'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file '720p.m4v'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file 'audio_128k.m4a'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file '360p.m4v'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file '1080p.m4v'.
[0316/093651:INFO:demuxer.cc(88)] Demuxer::Run() on file 'trick_1080p.m4v'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file 'trick_480p.m4v'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file 'audio_128k.m4a'.
[0316/093651:INFO:demuxer.cc(160)] Initialize Demuxer for file 'trick_1080p.m4v'.
[0316/093651:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/audio_48k.m4a'.
[0316/093651:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/trick_480p.m4v'.
[0316/093651:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/360p.m4v'.
[0316/093651:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/audio_128k.m4a'.
[0316/093651:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/480p.m4v'.
[0316/093651:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/trick_1080p.m4v'.
[0316/093651:ERROR:period.cc(223)] Failed to find original AdaptationSet for trick play.
[0316/093652:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/720p.m4v'.
[0316/093652:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'output/1080p.m4v'.
```

It appears the issue occurs if the output `trick_480p.m4v` is completing before any of the normal video tracks.  In this case, the audio was processed by `single_segment_segmenter.cc` first, but that doesn't seem to be enough.  Each time the command is run, the order could be different.

When sharing the same input file for the trick play track, this doesn't happen.  If the trick play track depends on other tracks, it should be sorted to be processed later.

**Comment by kqyang** [comment] 2020-03-16 17:38
@ngbrown In our current design of DASH TrickPlay feature, we expect the same input to be used for normal video, i.e. we do not expect to see a specialized input for trick play only. 

Is there a reason that you don't want to use the original input `480p.m4v`, `1080p.m4v` for trick play directly?

**Comment by ngbrown** [comment] 2020-03-16 23:39
I mentioned that my main video has I-frames every 6 seconds.  The standard convention seems to be not less than every 2 seconds.  There is obviously a bandwidth/quality trade-off with higher rates.

For the trick play, the Apple HLS authoring specification says the I-frames for trick play should be [1 fps, I-frame only](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices#2969507).

I also noticed, that it doesn't quite work when process finishes without error.  The `<EssentialProperty/>` is missing from the trick adaptation set, when it would normally be there when generated from a common video file.

```xml
<EssentialProperty schemeIdUri="http://dashif.org/guidelines/trickmode" value="1"/>
```

**Comment by kqyang** [comment] 2020-03-17 01:46
> I mentioned that my main video has I-frames every 6 seconds.

Ah, sorry, I missed that in your original comment.

That is a case we do not support right now. I'll change it to an enhancement request. It is not too difficult to support though. What we can do is if https://github.com/google/shaka-packager/blob/master/packager/mpd/base/period.cc#L221 fails, we can cache the trick play adaptation sets and search again when new AdaptationSets comes in. 

@sr1990 It is related to https://github.com/google/shaka-packager/pull/726. Let us know if you want to help on this one too!

**Comment by sr1990** [comment] 2020-03-17 07:38
Hey @kqyang, yes I would like to help. Let me try to reproduce the issue. @ngbrown Will it be possible to share the content?

**Comment by ngbrown** [comment] 2020-03-18 01:00
@sr1990 I tried to use a publicly available video, and it wasn't stopping on error, then I went back to the original video and my original scripts, and it doesn't stop on that one either, even repeatedly.  So definitely an intermittent problem.

The separate trick play adaptation set with the `<EssentialProperty/>` is still missing, so at least that is consistent.

Attached are the windows command scripts that are representative of what I am trying to do use for encoding then packaging.  You just need to supply ffmpeg and a video.

[test-encode-package.zip](https://github.com/google/shaka-packager/files/4346424/test-encode-package.zip)

**Comment by sr1990** [comment] 2020-03-20 08:44
@ngbrown I was able to reproduce the issue. 1 fps stream with 1 trick play factor is not creating a separate trickplay adaptation set because in  TrickPlayHandler::OnMediaSample (https://github.com/google/shaka-packager/blob/9a3ea747a40991c1cfb85bd163693270fb7d41d5/packager/media/trick_play/trick_play_handler.cc#L136) playback rate is stored only when a frame which is not a trickplay frame is encountered. In this case every frame is a trickplay frame, so playback rate is not set and that is why the generated AdaptationSet key is does not contain ":trickplay" in it.(https://github.com/google/shaka-packager/blob/9a3ea747a40991c1cfb85bd163693270fb7d41d5/packager/mpd/base/period.cc#L74).

I do not see the issue if trick_play_factor >1 for 1 fps stream along with PR https://github.com/google/shaka-packager/pull/736 that I am working on. 
@kqyang Please let me know if I am missing anything.

**Comment by ngbrown** [comment] 2020-03-20 19:52
I couldn't find any information on what `trick_play_factor` really meant, and what a value besides `1` would mean.  If it is set to `2` what does that do?

**Comment by kqyang** [comment] 2020-03-20 21:41
@sr1990 Thanks for looking into the problem. Yes, you are right. I think we can fix it by moving the setting of playback_rate to TrickPlayHandler::OnTrickFrame:

```diff
❯ gd
diff --git i/packager/media/trick_play/trick_play_handler.cc w/packager/media/trick_play/trick_play_handler.cc
index b6162162..1097d8a0 100644
--- i/packager/media/trick_play/trick_play_handler.cc
+++ w/packager/media/trick_play/trick_play_handler.cc
@@ -144,17 +144,6 @@ Status TrickPlayHandler::OnMediaSample(const MediaSample& sample) {
     }
   }

-  // Update this now as it may be sent out soon via the delay message queue.
-  if (total_trick_frames_ < 2) {
-    // At this point, video_info will be at the head of the delay message queue
-    // and can still be updated safely.
-
-    // The play back rate is determined by the number of frames between the
-    // first two trick play frames. The first trick play frame will be the
-    // first frame in the video.
-    video_info_->set_playback_rate(total_frames_);
-  }
-
   // If the frame is not a trick play frame, then take the duration of this
   // frame and add it to the previous trick play frame so that it will span the
   // gap created by not passing this frame through.
@@ -182,6 +171,17 @@ Status TrickPlayHandler::OnTrickFrame(const MediaSample& sample) {
     return Status::OK;
   }

+  // Update this now as it may be sent out soon via the delay message queue.
+  if (total_trick_frames_ == 2) {
+    // At this point, video_info will be at the head of the delay message queue
+    // and can still be updated safely.
+
+    // The play back rate is determined by the number of frames between the
+    // first two trick play frames. The first trick play frame will be the
+    // first frame in the video.
+    video_info_->set_playback_rate(total_frames_ - 1);
+  }
+
   // Send out all delayed messages up until the new trick play frame we just
   // added.
   Status s;
```

@ngbrown It is explained here: https://google.github.io/shaka-packager/html/documentation.html#stream-descriptors. It is the frame sampling rate. 2 means that every one of two key frames goes into the output.

**Comment by kqyang** [comment] 2020-03-24 19:16
@ngbrown Thanks to @sr1990's help, this is now fixed. Let us know if you are still seeing problems.

**Closed** 2020-03-24 19:15 UTC
Labels: enhancement, help wanted
