### ISSUE TITLE
AES-128 Encryption support

### ISSUE THREAD

**Issue by vengateshvengi** [google/shaka-packager#714] opened 2020-02-17 14:54 UTC
Is there any support for aes-128 encryption in shaka packager.
I am looking for hls live streaming with DRM support(widevine).but,the shaka packager used sample-aes algorithm.So,tell me whether any other option there for AES-128 encryption.

**Comment by kqyang** [comment] 2020-02-17 21:47
No. We do not support AES-128 for HLS. 

> I am looking for hls live streaming with DRM support(widevine).but,the shaka packager used sample-aes algorithm

Widevine HLS uses SAMPLE-AES. Here is an introduction article: https://medium.com/@takusemba/hls-with-widevine-for-android-de3f41027ed2.

Let us know if you have more questions.

**Comment by vengateshvengi** [comment] 2020-02-18 04:57
There is any option to implement samples-aes-ctr method in shaka packager

**Comment by kqyang** [comment] 2020-02-18 18:48
The encryption method is determined by protection_scheme (`--protection_scheme`): https://google.github.io/shaka-packager/html/tutorials/drm.html#general-encryption-options.

If `--protection_scheme` is `cenc`, SAMPLE-AES-CTR is used; otherwise if `--protection_scheme` is `cbcs`, SAMPLE-AES is used. `cenc`, i.e. SAMPLE-AES-CTR is the default.

**Comment by vengateshvengi** [comment] 2020-02-19 05:21
ya correct.But I want SAMPLE-AES-CTR  encryption method for live hls packaging.it's not working.
my running command:
packager-linux 'in=udp://192.168.20.3:50003,stream=audio,init_segment=/etc/ec/feed_path/test.com/mbcn/master/DEMO/audio_init.mp4,segment_template=/etc/ec/feed_path/test.com/mbcn/master/DEMO/audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' 'in=udp://192.168.20.3:50003,stream=video,init_segment=/etc/ec/feed_path/test.com/mbcn/master/DEMO/DEMO_init576Original.mp4,segment_template=/etc/ec/feed_path/test.com/mbcn/master/DEMO/DEMO576Original_$Number$.m4s,playlist_name=DEMO576Original.m3u8'  --segment_duration 2   --suggested_presentation_delay 2 --time_shift_buffer_depth 12 --strip_parameter_set_nalus=false  --preserved_segments_outside_live_window 20  --max_hd_pixels 8294400 --protection_scheme cenc --enable_widevine_encryption  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test  --content_id 7465737420636f6e74656e74206964   --signer widevine_test  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 --protection_systems Widevine --hls_master_playlist_output demo_master.m3u8
There is any problem in this command.

**Comment by kqyang** [comment] 2020-02-19 19:25
@vengateshvengi That looks correct to me. What problem are you seeing?

**Comment by vengateshvengi** [comment] 2020-02-20 04:19
ya But sometimes,it shows sample-aes encryption and sometimes sample-aes-ctr.That's why i am asking.I have seen your source code,you have aes-128 encryption method.then why its not supported .

**Comment by vengateshvengi** [comment] 2020-02-20 10:46
Do you have any idea about video scrambling process?

**Comment by kqyang** [comment] 2020-02-20 19:54
> But sometimes,it shows sample-aes encryption and sometimes sample-aes-ctr

Do you have a repro case on sample-aes?

> I have seen your source code,you have aes-128 encryption method.then why its not supported

It is a legacy format which we do not recommend. It is indeed supported in our HLS generator but we do not support encrypting content with AES-128.

**Comment by vengateshvengi** [comment] 2020-02-21 04:41
But i had changed the source code to force the encryption method as aes128 with widevine DRM.It is encrypted and m3u8 shows the key method as AES-128.It was decrypted and played well in exoplayer.
Is it correctly encrypted or not  ?

**Comment by kqyang** [comment] 2020-02-21 20:24
@vengateshvengi I don't think so unless you modified the encryption logic too. I am really surprised that it works in exoplayer.

**Comment by vengateshvengi** [comment] 2020-02-22 04:29
Ya,Its playing good in exoplayer.
Is there any way to validate encryption logic working correct?

**Comment by vengateshvengi** [comment] 2020-02-22 06:23
> @vengateshvengi I don't think so unless you modified the encryption logic too. I am really surprised that it works in exoplayer.

I am using widevine DRM with aes-128 encryption.whether it may be reason for playing in exoplayer

**Comment by kqyang** [comment] 2020-02-23 22:53
@vengateshvengi Can you share your modifications and the stream you generated?

**Comment by vengateshvengi** [comment] 2020-02-26 06:37
I had changed the encryption method as kaes128  in Encryptionparams class.

**Comment by kqyang** [comment] 2020-06-02 00:00
Mark it as a duplicate of #776.

**Closed by kqyang** 2020-06-02 00:00 UTC
Labels: question
