### ISSUE TITLE
Sidx atom missing the first offset bytes

### ISSUE THREAD

**Issue by crazyghost12** [google/shaka-packager#850] opened 2020-10-02 14:49 UTC
## System info
**Operating System**: Ubuntu 18.04
**Shaka Packager Version**: v2.4.0p2-c731217607-release

## Issue and steps to reproduce the problem

**Packager Command**: ./packager input=test.mp4,stream=audio,output=output.mp4,playlist_name=test.mpd --mpd_output master.mpd --segment_duration 1 --fragment_duration 1 --enable_raw_key_encryption --protection_scheme cenc --keys label=AUDIO:key_id=1d6c226cec8846378629f788fe180f2c:key=de0cfa0e2dcff081824a06027e4c0fe1 --iv a7871e0a616f9e14 --pssh 000000327073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED000000121210C713D43936FA9F1268005C9C83ED370D0000003470737368010000009A04F07998404286AB92E65BE0885F9500000001C713D43936FA9F1268005C9C83ED370D00000000

Extra steps to reproduce the problem?
(1) Once the shaka has run open the generated output.mp4 in mp4parser.com

What is the expected result?
As per ffmpeg starndard and the code at https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/movenc.c#L4696-L4719 the size of the sidx atom must be 40 bytes + (reference_count x 12) bytes.
Calculation for 40 bytes -> 4(size) + 4(sidx string) + 1(version) + 3(empty) + 4(reference ID) + 4(timescale) + 8(earliest presentation time) + 8(first offset) + 2(reserved) + 2(reference count)

What happens instead?
The sidx atom in the output.mp4 is 8 bytes short. Upon further investigation I found out that the 8 bytes for first_offset field are missing. Is this unexpected behavior or is my understanding about the atom flawed?

**Comment by kqyang** [comment] 2020-10-04 05:18
`sidx` box has two versions: version 0 and version 1. See the definition below.

```c
aligned(8) class SegmentIndexBox extends FullBox(‘sidx’, version, 0) {
  unsigned int(32) reference_ID;
  unsigned int(32) timescale;
  if (version==0) {
    unsigned int(32) earliest_presentation_time;
    unsigned int(32) first_offset;
  }
  else {
    unsigned int(64) earliest_presentation_time;
    unsigned int(64) first_offset;
  }
  unsigned int(16) reserved = 0;
  unsigned int(16) reference_count;
  for(i=1; i <= reference_count; i++)
  {
    bit (1) reference_type;
    unsigned int(31) referenced_size;
    unsigned int(32) subsegment_duration;
    bit(1) starts_with_SAP;
    unsigned int(3) SAP_type;
    unsigned int(28) SAP_delta_time;
  }
}
```

The size of version 0 is 8 bytes smaller. When generating `sidx` box, Shaka Packager computes in run time whether a version 0 box can be used (i.e. whether `earliest_presentation_time` and `first_offset` fits in 32 bits). If so, a version 0 box is used, otherwise a version 1 box is used: https://github.com/google/shaka-packager/blob/master/packager/media/formats/mp4/box_definitions.cc#L2699.

So, yes, it is working as intended.I'll close this bug, but feel free to reply if you still have questions.

**Closed by kqyang** 2020-10-04 05:18 UTC
Labels: needs triage
