### ISSUE TITLE
Support for AC-4 audio on packager

### ISSUE THREAD

**Issue by yotta-stu** [google/shaka-packager#705] opened 2020-01-30 12:00 UTC
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
Ubuntu 16.04.5
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
version 53aa775-release
## Issue and steps to reproduce the problem
Request support for Dolby AC-4 audio type. 
**Packager Command**:
sudo ./packager \
  'input=/home/packager/content/'$content',stream=video,init_segment='$out'/video/init-video.mp4,segment_template='$out'/video/$Number$.m4s' \
  'input=/home/packager/content/'$content',stream=1,init_segment='$out'/audio/init-audio.mp4,segment_template='$out'/audio/$Number$.m4s' \
  --segment_duration 1 \
  --generate_static_mpd \
  --allow_approximate_segment_timeline \
  --segment_template_constant_duration \
  --mpd_output $out/manifest.mpd

Extra steps to reproduce the problem?
(1) Run with MP4 content that contains AC-4 audio.
(2)

What is the expected result?
Would like support for the AC-4 audio type so it is packaged along with video.
What happens instead?
Error with unsupported audio format, see error log:

[0130/110559:WARNING:mp4_media_parser.cc(454)] Unsupported audio format 'ac-4' in stsd box.
[0130/110559:ERROR:audio_stream_info.cc(129)] Not implemented reached in static std::string shaka::media::AudioStreamInfo::GetCodecS                      tring(shaka::media::Codec, uint8_t)Codec: 0
[0130/110559:ERROR:mp4_muxer.cc(480)] Not implemented reached in bool shaka::media::mp4::MP4Muxer::GenerateAudioTrak(const shaka::me                      dia::AudioStreamInfo *, shaka::media::mp4::Track *, uint32_t) Unsupported audio codec 0
[0130/110559:ERROR:demuxer.cc(319)] Failed to process sample 1 11 (MUXER_FAILURE): Failed to generate trak.
[0130/110559:ERROR:mp4_media_parser.cc(790)] Failed to process the sample.
[0130/110559:ERROR:packager_main.cc(518)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file 
<Please attach the input files or email to shaka-packager-issues@google.com.>
via email.

**Comment by kqyang** [comment] 2020-01-30 18:34
@yotta-stu Do you have a sample AC-4 we can use for development?

**Comment by yotta-stu** [comment] 2020-01-31 12:37
You can download the content with AC-4 from this link (it will be active for 7 days)

 

https://we.tl/t-7PtB6FcK9O

 

Thanks,


Stuart

**Comment by kqyang** [comment] 2020-01-31 18:32
@yotta-stu Thanks!

**Comment by kqyang** [comment] 2020-04-22 17:29
This is a duplicate of #754.

**Closed by kqyang** 2020-04-22 17:29 UTC
Labels: enhancement, help wanted
