### ISSUE TITLE
Build failure with g++ on Ubuntu 17.10 due to deprecated call to readdir_r

### ISSUE THREAD

**Issue by l-law** [google/shaka-packager#286] opened 2017-11-03 10:11 UTC
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
Shaka Packager version is 72df5af150afb16e0d389f848865980458d668f7

### Build steps:
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=`pwd`/depot_tools:"$PATH"
gclient config https://www.github.com/google/shaka-packager.git --name=src
gclient sync -r 72df5af150afb16e0d389f848865980458d668f7
GYP_DEFINES='clang=0' gclient runhook
cd src
ninja -C out/Release

### What is the expected result?
Compile success

### What happens instead?
Failed with this log:

FAILED: obj/base/files/base.file_enumerator_posix.o 
c++ -MMD -MF obj/base/files/base.file_enumerator_posix.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=274369-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DUSE_SYMBOLIZE -DUSE_LIBPCI=1 -DUSE_NSS_CERTS=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DBASE_IMPLEMENTATION -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D_FORTIFY_SOURCE=2 -Igen -I../../packager -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-extra -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -B/work/ubuntu/shaka-packager/src/packager/third_party/binutils/Linux_x64/Release/bin -Wno-unused-local-typedefs -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-narrowing  -c ../../packager/base/files/file_enumerator_posix.cc -o obj/base/files/base.file_enumerator_posix.o
../../packager/base/files/file_enumerator_posix.cc: In static member function 'static bool base::FileEnumerator::ReadDirectory(std::vector<base::FileEnumerator::FileInfo>*, const base::FilePath&, bool)':
../../packager/base/files/file_enumerator_posix.cc:136:10: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
   while (readdir_r(dir, &dent_buf, &dent) == 0 && dent) {
          ^~~~~~~~~
In file included from /usr/include/features.h:419:0,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from ../../packager/base/files/file_enumerator.h:9,
                 from ../../packager/base/files/file_enumerator_posix.cc:5:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
../../packager/base/files/file_enumerator_posix.cc:136:41: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
   while (readdir_r(dir, &dent_buf, &dent) == 0 && dent) {
                                         ^
In file included from /usr/include/features.h:419:0,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from ../../packager/base/files/file_enumerator.h:9,
                 from ../../packager/base/files/file_enumerator_posix.cc:5:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
cc1plus: all warnings being treated as errors
[1115/1592] CXX obj/base/files/base.file_path.o

=======================================================================

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

### Compiler version
In environment CXX is set to /usr/bin/g++ and the version is:

$ /usr/bin/g++ --version
g++ (Ubuntu 6.4.0-4ubuntu1) 6.4.0 20170820
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Misc
boringssl used in this version of shaka-packager also has this deprecated call, in
src/packager/third_party/boringssl/src/decrepit/ssl/ssl_decrepit.c:157

Updating both chromium/base and boringssl still has build error

I tried to update chromium/base with following steps but it complained that base.gyp not found
sed -i 's/a34eabec0d807cf03dc8cfc1a6240156ac2bbd01/4d611f57d75e43c215fdd058c6da659e42b9da66/' src/DEPS
gclient sync

**Comment by kqyang** [comment] 2017-11-03 15:08
Thanks for reporting the problem! The boringssl issue should get resolved with a DEPS update. The Chromium base problem is more difficult as the problem is addressed in Chromium CL https://chromium.googlesource.com/chromium/src/+/c2fdc2710b700158ad46111be664eac7ede0fdce, which already switches from GYP to GN. We use GYP in Shaka Packager. 

Our long term plan is to switch from Chromium base to abseil (https://github.com/abseil/abseil-cpp). That will happen some time next year, which should address this issue.

For the time being, a possible temporary fix might be to roll Chromium base DEPS and write a chromium_base.gyp to make it work.

**Comment by l-law** [comment] 2017-11-06 04:22
Thanks for the response. For the temporary fix, will there be a schedule to write a chromium_base.gyp in shaka-packager?

By the way, I tried to manually patch Chromium base to replace readdir_r with readdir, but it results in some other build errors. Is gcc on Ubuntu a supported compiler of shaka-packager?

**Comment by kqyang** [comment] 2017-11-06 19:54
Yes, gcc on Ubuntu is supported. We don't have data points for other revisions of Ubuntu, but it works on Ubuntu 14.04 trusty.

> For the temporary fix, will there be a schedule to write a chromium_base.gyp in shaka-packager?

There is no immediate plan to fix the problem at this moment. It has to wait until Q1 2018. We'll likely just skip the temporary fix and go for the long term fix directly, unless there is an urgency from you guys - let us know if that is the case.

Btw, does it work with clang enabled?

**Comment by l-law** [comment] 2017-11-07 04:13
Actually my original issue was a crash when assigning a string value to segment_template in shaka::media::MuxerOptions, which I believe is not a bug in codes, but rather a compilation/linking issue. I have a C++ program which links to static library version of shaka-packager. My program is compiled with g++(the same one as stated in issue), and shaka-packager is compiled with clang. My first guess was that clang and g++ used different c++ std lib, but I could not find a strong proof of this, so I tried to use the same compiler for both, and then found the compile issue for shaka-packager.

So for my case, when clang is enabled, shaka-packager can build, but it crashes in std::string assignment.

**Comment by kqyang** [comment] 2017-11-07 05:37
I see. It does sound like a linking issue. Can you try on a lower version of Ubuntu?

**Comment by l-law** [comment] 2017-11-14 02:38
Shaka-packager can be built on lower version of Ubuntu, like 14.04, with a older version of glibc. However, some of my other projects cannot be built there.

I want to give a try to -Wno-deprecated-declarations to skip this build error first, how can I add this flag when compiling shaka-packager?

**Comment by kqyang** [comment] 2017-11-21 00:11
Try add it in https://github.com/google/shaka-packager/blob/master/packager/common.gypi#L23. Then run

```bash
> gclient runhooks
> ninja -C out/Release
```

**Comment by l-law** [comment] 2017-11-28 04:01
My final solution is to fall back onto Ubuntu 16.04, where I am able to build shaka-packager with g++, by adding `GYP_DEFINES='clang=0' CXXFLAGS='-Wno-unused-variable'` when running `gclient runhooks`.

FYI, build error without `-Wno-unused-variable` on Ubuntu 16.04 would be: 

> In file included from ../../packager/app/fixed_key_encryption_flags.h:14:0,
>                  from ../../packager/app/fixed_key_encryption_flags.cc:9:
> ../../packager/app/gflags_hex_bytes.h:41:15: error: 'shaka_gflags_extension::hex_validator_key_id' defined but not used [-Werror=unused-variable]
>    static bool hex_validator_##name = gflags::RegisterFlagValidator( \
>                ^
> ../../packager/app/fixed_key_encryption_flags.cc:19:1: note: in expansion of macro 'DEFINE_hex_bytes'
>  DEFINE_hex_bytes(key_id, "", "Key id in hex string format.");

**Closed** 2017-12-07 21:37 UTC
Labels: bug

**Comment by kqyang** [comment] 2017-12-08 00:08
@l-law Thanks for the info. This should now be fixed. It should now work in Ubuntu 17 too.
