### ISSUE TITLE
Splitting vtt files according to timeline

### ISSUE THREAD

**Issue by fuzing** [google/shaka-packager#302] opened 2017-12-04 19:29 UTC
Good morning:

I am attempting to find a unified solution for packaging aac/h265/vtt as both DASH and HLS, with fmp4, for VOD.

shaka packager seems like a great solution but it appears there may be a number of issues with packaging subtitles/captions:
  1. vtt files appear to be passed through without segmenting them, as defined by the spec/s (I'm using 3 second segments and have played with very simple .vtt files that overlap segments in numerous combinations of ways).

  2. no .m3u8 playlists are created for the vtt files, and (clearly) no reference is made in the master playlist file.

Is there a timeline for work on this area?

Thank you!

For posterity, I'm building off the master, and what follows is my command line (sans backslashes etc.).

shaka-packager
      input=video-720-h265.mp4,stream=video,init_segment=init_v720.mp4,segment_template=v720_$Number$.mp4,playlist_name=v720.m3u8
      input=video-360-h265.mp4,stream=video,init_segment=init_v360.mp4,segment_template=v360_$Number$.mp4,playlist_name=v360.m3u8
      input=video-180-h265.mp4,stream=video,init_segment=init_v180.mp4,segment_template=v180_$Number$.mp4,playlist_name=v180.m3u8
      input=audio-1-aac.m4a,stream=audio,lang=en,init_segment=init_aud-en.m4a,segment_template=aud-en_$Number$.m4a,hls_name=English,hls_group_id=audio,playlist_name=audio-en.m3u8
      input=audio-2-aac.m4a,stream=audio,lang=fr,init_segment=init_aud-fr.m4a,segment_template=aud-fr_$Number$.m4a,hls_name=French,hls_group_id=audio,playlist_name=audio-fr.m3u8
      input=audio-3-aac.m4a,stream=audio,lang=es,init_segment=init_aud-es.m4a,segment_template=aud-es_$Number$.m4a,hls_name=Spanish,hls_group_id=audio,playlist_name=audio-es.m3u8
      input=en.vtt,stream=text,lang=en,init_segment=init_en.vtt,segment_template=eng_$Number$.vtt,playlist_name=en.m3u8
      input=es.vtt,stream=text,lang=es,init_segment=init_es.vtt,segment_template=spa_$Number$.vtt,playlist_name=es.m3u8
      input=fr.vtt,stream=text,lang=fr,init_segment=init_fr.vtt,segment_template=fre_$Number$.vtt,playlist_name=fr.m3u8
      --segment_duration 3
      --hls_playlist_type VOD
      --hls_master_playlist_output lecture.m3u8
      --generate_static_mpd
      --mpd_output lecture.mpd

(I've also tried this command without the --mpd.....  lines [i.e. HLS only], in the interests of simplifying the tests - the results are the same).

**Comment by kqyang** [comment] 2017-12-04 20:49
@fuzing It is a work-in-progress. Our target is to deliver the feature in early Jan 2018. Stay tuned.

**Comment by fuzing** [comment] 2017-12-04 22:32
Thank you - will do!

**Comment by kqyang** [comment] 2018-02-07 21:54
Duplicate of #205.  It is now supported. Note that Apple requires segmented vtt in text format and DASH requires segmented vtt in fmp4. So although we support both in Shaka Packager, there is no way to package a segmented VTT that works with both HLS/DASH. We are exploring ways to package for both DASH and HLS in a single command.

Close this issue as it is resolved.

@fuzing Feel free to verify the change. Let us know if you find any problems. Thanks.

**Closed by kqyang** 2018-02-07 21:54 UTC
Labels: enhancement
