### ISSUE TITLE
Webvtt for hls.

### ISSUE THREAD

**Issue by Moiahbabi** [google/shaka-packager#274] opened 2017-09-28 17:27 UTC
## System info
**Operating System**: Ubuntu 17.04
**Shaka Packager Version**: packager version 6c0f2bebef-release

## Issue and steps to reproduce the problem

**Packager Command**:
```

mkdir media
mkdir media/mp4
mkdir media/mp4/subtitle
mkdir media/webm
mkdir media/webm/subtitle

cd media/mp4
packager \
input=../../video_360p_1000kbps.mp4,stream=video,output=video_360p_1000kbps.mp4,playlist_name=_video_360p_1000kbps.m3u8 \
input=../../audio_128kbps.mp4,stream=audio,output=audio_128kbps.mp4,playlist_name=_audio_128kbps.m3u8,hls_group_id=audio,hls_name=ENGLISH \
input=../../subtitle/subtitle_en.webvtt,stream=text,output=subtitle/en.webvtt,language=en,playlist_name=_subtitle_en.m3u8 \
--mpd_output __manifest_Full.mpd \
--hls_master_playlist_output="__playlist_Full.m3u8" \
--hls_base_url="" \
--min_buffer_time 4 \
--segment_duration 4
cd ../../

````
Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
the following files should be created:

- `__playlist_Full.m3u8`
- `_audio_128kbps.m3u8`
- `_video_360p_1000kbps.m3u8`
- `_subtitle_en.m3u8`

 `_subtitle_en.m3u8` should be created and included in the` __playlist_Full.m3u8`

What happens instead?
 - `__playlist_Full.m3u8`
 - `_audio_128kbps.m3u8`
 - `_video_360p_1000kbps.m3u8`
 - `_subtitle_en.m3u8` --> was not created.

` __playlist_Full.m3u8` has only  `_audio_128kbps.m3u8` and `_video_360p_1000kbps.m3u8`

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

So I am trying to create DASH and HLS playlists from the same mp4 files, instead of segmented mp4s for HLS. so far the mpd manifest has all files referenced (video, audio, and webvtt files), but with the HLS playlist, only video and audio playlist are created and referenced in the master playlist.
so, are the commands above correct? or is there something missing?

Thank you.

**Comment by kqyang** [comment] 2017-09-28 17:43
That is not supported yet. We are working on it right now.

**Comment by kqyang** [comment] 2017-09-28 21:50
Duplicate of #205

**Closed by kqyang** 2017-09-28 21:50 UTC
Labels: enhancement
