### ISSUE TITLE
Windows 64bit builds are broken.

### ISSUE THREAD

**Issue by CCC-EE** [google/shaka-packager#184] opened 2016-12-29 23:20 UTC
**Windows 10 Pro** / **1607** / **14393.576**

**Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3**

Using the following 

    GYP_DEFINES="target_arch=x64"
    GYP_GENERATORS=ninja,msvs
    ninja -C out\Debug_x64

Results in failed builds under Ninja/VS2015. Numerous warnings trigger errors:

    error C2220: warning treated as error - no 'object' file generated
    .
    .
    .

**Instead** of resetting WarnAsError globally in `common.gypi` (a quick and dirty work around) I went ahead and fixed all the errors (see **.cc** files impacted in list below).

          'VCCLCompilerTool': {
            'WarnAsError': 'false',
            'DisableSpecificWarnings': ['4125']
          },

An _additional failure_ occurs when attempting to build with VS.  Part of the CURL library is built in such a way that `gclient runhooks` generates an 'inappropriate' MSBUILD file for VS2015 (the only version I tested to date).

The fix is simple (and didn't impact the Ninja builds):

      'target_name': 'curl_config',
      'type': 'none',
      'sources': [
        'config/curl/curlbuild.h',
      ],

I am in the process of getting a CLA approved. The full change involves the following files:

        modified:   .gitignore
        modified:   packager/media/base/container_names_unittest.cc
        modified:   packager/media/base/producer_consumer_queue_unittest.cc
        modified:   packager/media/codecs/aac_audio_specific_config.cc
        modified:   packager/media/codecs/ec3_audio_util.cc
        modified:   packager/media/codecs/es_descriptor.cc
        modified:   packager/media/codecs/nal_unit_to_byte_stream_converter.cc
        modified:   packager/media/codecs/vp8_parser.cc
        modified:   packager/media/codecs/vp9_parser.cc
        modified:   packager/media/codecs/vp_codec_configuration_record.cc
        modified:   packager/media/formats/mp2t/adts_header.cc
        modified:   packager/media/formats/mp2t/es_parser_adts.cc
        modified:   packager/media/formats/mp2t/es_parser_h264_unittest.cc
        modified:   packager/media/formats/mp2t/es_parser_h26x_unittest.cc
        modified:   packager/media/formats/mp2t/mp2t_media_parser_unittest.cc
        modified:   packager/media/formats/mp2t/program_map_table_writer.cc
        modified:   packager/media/formats/mp2t/ts_packet_writer_util.cc
        modified:   packager/media/formats/mp2t/ts_writer.cc
        modified:   packager/media/formats/mp4/box_definitions.cc
        modified:   packager/media/formats/mp4/box_definitions_unittest.cc
        modified:   packager/media/formats/mp4/encrypting_fragmenter.cc
        modified:   packager/media/formats/mp4/fragmenter.cc
        modified:   packager/media/formats/mp4/mp4_media_parser.cc
        modified:   packager/media/formats/mp4/mp4_media_parser_unittest.cc
        modified:   packager/media/formats/mp4/mp4_muxer.cc
        modified:   packager/media/formats/mp4/multi_segment_segmenter.cc
        modified:   packager/media/formats/mp4/segmenter.cc
        modified:   packager/media/formats/mp4/track_run_iterator.cc
        modified:   packager/media/formats/mp4/track_run_iterator_unittest.cc
        modified:   packager/media/formats/webm/encryptor.cc
        modified:   packager/media/formats/webm/segmenter_test_base.cc
        modified:   packager/media/formats/webm/tracks_builder.cc
        modified:   packager/media/formats/webm/webm_cluster_parser.cc
        modified:   packager/media/formats/webm/webm_cluster_parser_unittest.cc
        modified:   packager/media/formats/webm/webm_parser.cc
        modified:   packager/media/formats/webm/webm_parser_unittest.cc
        modified:   packager/media/formats/webm/webm_tracks_parser_unittest.cc
        modified:   packager/media/formats/wvm/wvm_media_parser.cc
        modified:   packager/media/formats/wvm/wvm_media_parser_unittest.cc
        modified:   packager/media/test/packager_test.cc
        modified:   packager/third_party/curl/curl.gyp

I can build under Linux as well, but OS X will take a bit longer to setup. (if required)

**Comment by kqyang** [comment] 2017-01-03 21:21
+ @hchen1506 

@CCC-EE Thanks for working on this. This is a duplicate of #168 and @hchen1506 is already working on it. The fix is almost done and will be submitted some time this week.

Again, we really appreciate your help!

**Closed by kqyang** 2017-01-03 21:21 UTC

**Comment by CCC-EE** [comment] 2017-01-04 01:51
Well, given that #168 was nearly 2 months old (and now is), I really couldn't wait for a fix. Let me know if you are interested in me sending a pull request. Our 'legal' folks are OOO until next week, but I have my own personal account that I can submit this on.  Took me about an hour.  Have no idea why it would take > than two months.

**Comment by kqyang** [comment] 2017-01-07 02:21
Yah, that is unfortunate :( There were some concerns on the proper way to fix the issue. It was then delayed because of the holiday break. The commit has been merged: https://github.com/google/shaka-packager/commit/93fe5457bf183d5e75482b3d6c3b8599d699ee0b. Let us know if you still see issues.

Again, thanks for working on this!
