### ISSUE TITLE
"Unknown field in stream descriptor ("dash_roles")."

### ISSUE THREAD

**Issue by salmoro** [google/shaka-packager#673] opened 2019-10-30 17:17 UTC
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v2.3.0-5bf8ad5ed5-release

## Issue and steps to reproduce the problem
Packaging dash works perfectly well until I add `dash_roles=alternate` or `roles=alternate` where packager throws: `Unknown field in stream descriptor ("roles")`

**Comment by kqyang** [comment] 2019-10-30 17:45
The feature is implemented and will be included in v2.4 release. We are planning to release v2.4 some time this month (I understand that v2.4 release has been delayed multiple times due to our resource constraints. We'll try our best to make sure the release v2.4 in Nov).

Alternatively, you may compile Shaka Packager yourself from ToT or use the latest docker image.

I'll mark it as a duplicate of the original feature request for dash_roles: https://github.com/google/shaka-packager/issues/565. Let's know if you have other questions.

**Closed by kqyang** 2019-10-30 17:46 UTC
Labels: needs triage

**Comment by salmoro** [comment] 2019-10-30 19:05
@kqyang Great! Thanks for the prompt response.
