### ISSUE TITLE
edash pakager FOURCC_WIDE = 0x77696465 issue

### ISSUE THREAD

**Issue by guillaumemarc** [google/shaka-packager#117] opened 2016-07-08 07:41 UTC
we try to encripted a video in mp42 x264 but edash pakager not alowed FOURCC_WIDE

we see on edash pakager

edash-packager/packager/media/formats/mp4/box_reader.cc
// static
bool BoxReader::IsValidTopLevelBox(const FourCC& type) {
  switch (type) {
    case FOURCC_ftyp:
    case FOURCC_pdin:
    case FOURCC_bloc:
    case FOURCC_moov:
    case FOURCC_moof:
    case FOURCC_mfra:
    case FOURCC_mdat:
    case FOURCC_free:
    case FOURCC_skip:
    case FOURCC_meta:
    case FOURCC_meco:
    case FOURCC_styp:
    case FOURCC_sidx:
    case FOURCC_ssix:
    case FOURCC_prft:
      return true;
    default:
      // Hex is used to show nonprintable characters and aid in debugging
      LOG(ERROR) << "Unrecognized top-level box type 0x" << std::hex << type;
      return false;
  }

}

any raison to not suport FOURCC_WIDE?

**Comment by kqyang** [comment] 2016-07-08 17:05
This is a duplicate of issue #110. It should be fixed now. Please try either version [v1.4.1](https://github.com/google/shaka-packager/releases/tag/v1.4.1) or latest code in master branch.

I'll close the issue. Feel free to re-open it if you are seeing problems. Thanks!

**Closed by kqyang** 2016-07-08 17:05 UTC
