### ISSUE TITLE
Whether I can limit subtitle stream segments length?

### ISSUE THREAD

**Issue by UpTownCat** [google/shaka-packager#458] opened 2018-08-23 04:04 UTC
## System info
**Operating System**: CentOS Linux 7
**Shaka Packager Version**: v2.1.1-ce3e808060-release

## Issue and steps to reproduce the problem

**Packager Command**:

packager --segment_duration 6 --fragment_duration 6 --allow_approximate_segment_timeline \
	'in=debug.mp4,stream=audio,init_segment=subtitle/dash/subtitle_test/audio_init.mp4,segment_template=subtitle/dash/subtitle_test/audio_$Number$.m4s' \
	'in=qc.vtt,stream=text,lang=eng,init_segment=subtitle/dash/subtitle_test/subtitle1_init.mp4,segment_template=subtitle/dash/subtitle_test/subtitle1_$Number$.m4s' \
	--generate_static_mpd --default_language eng --mpd_output subtitle/dash/subtitle_test.mpd

What is the expected result?
>       
          <SegmentTimeline>
            <S t="0" d="6000" r="7"/>
          </SegmentTimeline>
What happens instead?
I found subtitle segment duration is not same. mpd result is like this:

>       
          <SegmentTimeline>
            <S t="0" d="46865"/>
            <S t="46865" d="2599"/>
            <S t="49464" d="15338"/>
            <S t="64802" d="2110"/>
            <S t="66912" d="46141"/>
            <S t="113053" d="4143"/>
            <S t="117196" d="3437"/>
            <S t="120633" d="7264"/>
          </SegmentTimeline>

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment] 2018-08-23 04:35
It should have been fixed in the latest revision. Can you try v2.2.0?

**Comment by UpTownCat** [comment] 2018-08-23 06:31
@kqyang It works fine now. Thanks lot😄

**Closed** 2018-08-23 06:32 UTC
Labels: needs triage

**Comment by kqyang** [comment] 2018-08-23 16:32
Mark it as a duplicate of https://github.com/google/shaka-packager/issues/382.
